server:
  port: 8080

spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter
    username: root
    password: zzz

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false